[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist/spa"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
